(function(global){
  "use strict";
  const DEFAULT_ROUTES=[
    {id:"baegot-life-loop",area:"배곧동",name:"배곧생명공원 물빛 루프",distance:3.2,duration:28,difficulty:"쉬움",surface:"공원 산책로",summary:"배곧생명공원의 수변과 잔디광장을 한 바퀴 도는 입문용 순환 코스",highlights:["수변 풍경","평탄한 구간","화장실·주차장"],basis:"배곧생명공원 시설 좌표 기반 MVP 추천 동선",points:[[14,69],[16,62],[22,60],[27,66],[24,74],[17,76],[14,69]]},
    {id:"okgu-park-loop",area:"정왕동",name:"옥구공원 초록 언덕 루프",distance:2.8,duration:25,difficulty:"보통",surface:"공원길·완만한 언덕",summary:"한국정원과 조가비무대를 지나 옥구공원의 녹지를 연결하는 코스",highlights:["한국정원","완만한 오르막","운동시설"],basis:"옥구공원 시설 좌표 기반 MVP 추천 동선",points:[[41,70],[43,62],[49,59],[55,65],[54,74],[47,78],[41,70]]},
    {id:"oido-history-coast",area:"정왕동",name:"오이도 역사·해안 코스",distance:4.6,duration:42,difficulty:"보통",surface:"해안 보행로·공원길",summary:"오이도 선사유적공원과 해안 방향의 주요 지점을 연결하는 풍경 코스",highlights:["선사유적공원","서해 풍경","노을 추천"],basis:"시흥시 오이도 공원·해안 지점 기반 MVP 추천 동선",points:[[70,67],[72,59],[79,56],[87,62],[89,73],[82,78],[74,75],[70,67]]},
    {id:"sincheon-park-link",area:"신천동",name:"신천 도심공원 연결 코스",distance:3.6,duration:33,difficulty:"쉬움",surface:"도심 보행로·공원길",summary:"신천공원에서 둥지공원·바람길공원 방향으로 이어지는 생활권 코스",highlights:["도심 접근성","여러 공원","가벼운 야간런"],basis:"신천동 공원 시설 좌표 기반 MVP 추천 동선",points:[[52,22],[57,13],[65,11],[70,17],[68,25],[61,29],[55,27],[52,22]]},
    {id:"eungye-lake-loop",area:"은행동",name:"은계호수공원 산뜻 루프",distance:2.4,duration:22,difficulty:"쉬움",surface:"호수공원 산책로",summary:"은계호수공원 수변을 중심으로 짧고 가볍게 반복할 수 있는 코스",highlights:["호수 풍경","카페 접근성","평탄한 루프"],basis:"은계호수공원 시설 좌표 기반 MVP 추천 동선",points:[[78,22],[82,13],[89,12],[94,19],[92,28],[84,31],[78,22]]},
    {id:"daeya-eungye-forest",area:"대야동",name:"대야–은계숲 그린 코스",distance:4.1,duration:38,difficulty:"보통",surface:"공원길·생활도로",summary:"대야공원에서 은계공원과 은계숲생태공원 방향을 연결하는 녹지 코스",highlights:["연속된 공원","중거리 훈련","생활권 접근"],basis:"대야·은계권 공원 시설 좌표 기반 MVP 추천 동선",points:[[16,24],[20,13],[29,10],[37,16],[39,27],[31,32],[22,31],[16,24]]}
  ];
  let frame=null,routes=DEFAULT_ROUTES,mount=null,dialog=null;
  const q=(selector,root=document)=>root.querySelector(selector);
  function fit(points,width=100,height=64,padding=8){const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),scale=Math.min((width-padding*2)/Math.max(maxX-minX,1),(height-padding*2)/Math.max(maxY-minY,1)),offsetX=(width-(maxX-minX)*scale)/2,offsetY=(height-(maxY-minY)*scale)/2;return points.map(([x,y])=>[offsetX+(x-minX)*scale,offsetY+(y-minY)*scale]);}
  function stop(){if(frame)cancelAnimationFrame(frame);frame=null;}
  function animate(){stop();const path=q(".rc-path",dialog),runner=q(".rc-runner",dialog);if(!path||!runner)return;const length=path.getTotalLength();path.style.strokeDasharray=String(length);path.style.strokeDashoffset=String(length);path.getBoundingClientRect();path.style.strokeDashoffset="0";if(matchMedia("(prefers-reduced-motion: reduce)").matches){const point=path.getPointAtLength(length*.55);runner.setAttribute("transform",`translate(${point.x} ${point.y})`);return;}const start=performance.now()+450,duration=7000;function move(now){const progress=Math.min(1,Math.max(0,(now-start)/duration)),point=path.getPointAtLength(length*progress),next=path.getPointAtLength(Math.min(length,length*progress+.5)),previous=path.getPointAtLength(Math.max(0,length*progress-.5)),angle=progress<1?Math.atan2(next.y-point.y,next.x-point.x)*180/Math.PI:Math.atan2(point.y-previous.y,point.x-previous.x)*180/Math.PI;runner.setAttribute("transform",`translate(${point.x} ${point.y}) rotate(${angle})`);if(progress<1)frame=requestAnimationFrame(move);else frame=null;}frame=requestAnimationFrame(move);}
  function open(route){const points=fit(route.points),pointText=points.map(p=>p.map(v=>v.toFixed(2)).join(",")).join(" "),[sx,sy]=points[0],[fx,fy]=points[points.length-1];q("[data-rc-area]",dialog).textContent=route.area;q("[data-rc-difficulty]",dialog).textContent=route.difficulty;q("[data-rc-title]",dialog).textContent=route.name;q("[data-rc-summary]",dialog).textContent=route.summary;q("[data-rc-distance]",dialog).textContent=`${route.distance} km`;q("[data-rc-duration]",dialog).textContent=`${route.duration}분`;q("[data-rc-surface]",dialog).textContent=route.surface;q("[data-rc-tags]",dialog).innerHTML=route.highlights.map(x=>`<span># ${x}</span>`).join("");q("[data-rc-basis]",dialog).textContent=route.basis;q("[data-rc-svg]",dialog).innerHTML=`<defs><linearGradient id="rc-gradient"><stop stop-color="#79c892"/><stop offset=".55" stop-color="#176b4d"/><stop offset="1" stop-color="#0d3f2c"/></linearGradient><filter id="rc-shadow"><feDropShadow dx="0" dy="1" stdDeviation="1" flood-opacity=".28"/></filter></defs><g class="rc-grid"><path d="M-5 13H105M-5 31H105M-5 50H105M18-5V69M43-5V69M72-5V69"/><path d="M-10 60L34-8M28 70L83-8M61 70L110 11"/></g><polyline class="rc-halo" points="${pointText}"/><polyline class="rc-path" points="${pointText}"/><g class="rc-end" transform="translate(${sx} ${sy})"><circle r="3.2"/><text y=".9">S</text></g><g class="rc-end rc-finish" transform="translate(${fx} ${fy})"><circle r="3.2"/><text y=".9">F</text></g><g class="rc-runner" filter="url(#rc-shadow)"><circle cy="-2.6" r="1.55"/><path d="M0-1L-1 2.2M-.2.1L2 1.1M-1 2.2L-2.5 4.7M-1 2.2L1.1 4.2M-.4-.1L-2.3 1"/></g>`;if(!dialog.open)dialog.showModal();requestAnimationFrame(animate);}
  function template(){return `<section class="rc-shell"><header class="rc-heading"><div><small>RUN SIHEUNG</small><h1>시흥시 추천 러닝코스</h1></div><p>코스를 선택하면 상세 팝업에서 러너가 동선을 따라 한 번 움직입니다.</p></header><div class="rc-list"></div></section><dialog class="rc-dialog"><button class="rc-close" type="button" aria-label="닫기">×</button><header class="rc-dialog-head"><div><small>LIVE COURSE PREVIEW</small><div class="rc-badges"><span data-rc-area></span><span data-rc-difficulty></span></div><h2 data-rc-title></h2><p data-rc-summary></p></div><button class="rc-replay" type="button">▶ 움직임 다시 보기</button></header><div class="rc-dialog-grid"><div class="rc-map"><svg data-rc-svg viewBox="0 0 100 64" aria-label="러닝코스 동선"></svg><div class="rc-live"><i></i>LIVE ROUTE</div><div class="rc-hint">움직이는 러너를 따라 코스를 미리 살펴보세요</div></div><aside class="rc-detail"><div class="rc-detail-stats"><article><small>거리</small><strong data-rc-distance></strong></article><article><small>예상 시간</small><strong data-rc-duration></strong></article><article><small>노면</small><strong data-rc-surface></strong></article></div><section><small>코스 포인트</small><div class="rc-tags" data-rc-tags></div></section><section><small>동선 산정 기준</small><p data-rc-basis></p></section><section class="rc-safety"><strong>출발 전 확인</strong><p>실제 통행 가능 여부와 조명·공사·날씨를 현장에서 다시 확인해 주세요.</p></section></aside></div></dialog>`;}
  function init(options={}){mount=typeof options.mount==="string"?document.querySelector(options.mount):options.mount;if(!mount)throw new Error("러닝코스 모듈을 넣을 mount 요소를 찾지 못했습니다.");routes=options.routes||DEFAULT_ROUTES;mount.innerHTML=template();dialog=q(".rc-dialog",mount);q(".rc-list",mount).innerHTML=routes.map(r=>`<button class="rc-card" data-route="${r.id}" type="button"><div class="rc-preview"><svg viewBox="0 0 104 90"><polyline points="${r.points.map(p=>p.join(",")).join(" ")}"/><circle cx="${r.points[0][0]}" cy="${r.points[0][1]}" r="2"/></svg><span>${r.area}</span></div><div class="rc-card-body"><div class="rc-card-top"><span>${r.area}</span><b>${r.difficulty}</b></div><h3>${r.name}</h3><p>${r.summary}</p><div class="rc-stats"><span>${r.distance}km</span><span>${r.duration}분</span></div><div class="rc-action">상세 코스 보기 <span>↗</span></div></div></button>`).join("");mount.addEventListener("click",event=>{const card=event.target.closest("[data-route]");if(card)open(routes.find(r=>r.id===card.dataset.route));if(event.target.closest(".rc-close")){stop();dialog.close();}if(event.target.closest(".rc-replay"))animate();});dialog.addEventListener("click",event=>{if(event.target===dialog){stop();dialog.close();}});dialog.addEventListener("close",stop);}
  global.RunningCourse={init,open,stop,DEFAULT_ROUTES};
})(window);
